[build]
  publish = "output/"
  command = "git submodule update --init --recursive && BRIDGETOWN_ENV=production ./bin/bridgetown deploy"

[[redirects]]
  from = "/cfp"
  to = "https://www.papercall.io/rubyconfth2022"
  
[[redirects]]
  from = "/tickets"
  to = "https://www.eventpop.me/e/13417/rubyconfth-2022"

[[redirects]]
  from = "/tickets/fbpromo"
  to = "https://www.eventpop.me/e/13417/rubyconfth-2022?discount_code=FBPROMO"
  
[[redirects]]
  from = "/sponsors"
  to = "https://drive.google.com/file/d/1Rgt9qWPaaMf6juoEHyLF_mnltm915IBh/view?usp=sharing"
