s3_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
s3_secret: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
s3_bucket: <%= ENV['AWS_S3_BUCKET_NAME'] %>

index_document: index.html
error_document: 404.html

s3_endpoint: <%= ENV['AWS_S3_BUCKET_ENDPOINT'] %>

cloudfront_distribution_id: <%= ENV['AWS_CLOUDFRONT_ID'] %>
cloudfront_distribution_config:
 default_cache_behavior:
   min_ttl: <%= 60 * 60 * 24 %>
 aliases:
   quantity: 1
   items:
     - <%= ENV['AWS_S3_BUCKET_NAME'] %>
     - www.<%= ENV['AWS_S3_BUCKET_NAME'] %>

max_age: 120
gzip: true

#exclude_from_upload:
##  - pages/page-name
